[theme]
base="light"
primaryColor="#3993dd"
backgroundColor="#eaeaea"
secondaryBackgroundColor="#D4D4D4"
font="monospace"

[server]
maxUploadSize = 5
enableXsrfProtection=false # IMPORTANTE FALLO STREAMLIT ELIMINAR CUANDO SEA CORREGIDO

[client]
showSidebarNavigation = false
